### ISSUE TITLE
xDhcpServer and xDnsServer Forks

### ISSUE THREAD

**Issue by ryanspletzer** [iainbrighton/PSHSummit-Man-vs-Testlab#1]
Hey @iainbrighton as I'm going through this example from your talk in conjunction with latest Lability, I noticed in [TLGBaseConfiguration.ps1](https://github.com/iainbrighton/PSHSummit-Man-vs-Testlab/blob/master/TLGBaseConfiguration.ps1):

```
Import-DscResource -Module xDHCPServer;                 ## REQUIRES: https://github.com/iainbrighton/xDhcpServer (due to xDhcpServerAuthorization)
Import-DscResource -Module xDNSServer;                  ## REQUIRES: https://github.com/iainbrighton/xDnsServer/tree/TestLabGuides (due to xDnsServerPrimaryZone)
```

Are these forks still necessary to use or is it safe to use the base ones at this point?

**Comment by iainbrighton** [comment]
@ryanspletzer You can now use the official DSC resources as the required functionality has since been merged in :smile:
